# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b65cc31cb02e4ecdeb1844b5f20b654ee577272e1dfb44ddc5ca9915e8a1fe6381cfaa2fae92eec632c8f1b8ad425d37f301b853e994f0e73137ce19c453fe

test:
  secret_key_base: 3283cb3c875707ff0c554b9fcead67a75012277e678b912d24685184787eda7f09e1caaee5ee28b8df783decd7ec10df62f0c046b00fac938d884bb505e363b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
